// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: txn.proto

#include "txn.pb.h"
#include "txn.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace zera_txn {

static const char* TXNService_method_names[] = {
  "/zera_txn.TXNService/Coin",
  "/zera_txn.TXNService/Mint",
  "/zera_txn.TXNService/ItemMint",
  "/zera_txn.TXNService/Contract",
  "/zera_txn.TXNService/GovernProposal",
  "/zera_txn.TXNService/GovernVote",
  "/zera_txn.TXNService/SmartContract",
  "/zera_txn.TXNService/SmartContractExecute",
  "/zera_txn.TXNService/SmartContractInstantiate",
  "/zera_txn.TXNService/CurrencyEquiv",
  "/zera_txn.TXNService/AuthCurrencyEquiv",
  "/zera_txn.TXNService/ExpenseRatio",
  "/zera_txn.TXNService/NFT",
  "/zera_txn.TXNService/ContractUpdate",
  "/zera_txn.TXNService/Foundation",
  "/zera_txn.TXNService/DelegatedVoting",
  "/zera_txn.TXNService/Quash",
  "/zera_txn.TXNService/FastQuorum",
  "/zera_txn.TXNService/Revoke",
  "/zera_txn.TXNService/Compliance",
  "/zera_txn.TXNService/BurnSBT",
  "/zera_txn.TXNService/Allowance",
};

std::unique_ptr< TXNService::Stub> TXNService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TXNService::Stub> stub(new TXNService::Stub(channel, options));
  return stub;
}

TXNService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Coin_(TXNService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Mint_(TXNService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ItemMint_(TXNService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Contract_(TXNService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GovernProposal_(TXNService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GovernVote_(TXNService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SmartContract_(TXNService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SmartContractExecute_(TXNService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SmartContractInstantiate_(TXNService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CurrencyEquiv_(TXNService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AuthCurrencyEquiv_(TXNService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExpenseRatio_(TXNService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NFT_(TXNService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ContractUpdate_(TXNService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Foundation_(TXNService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DelegatedVoting_(TXNService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Quash_(TXNService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FastQuorum_(TXNService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Revoke_(TXNService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Compliance_(TXNService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BurnSBT_(TXNService_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Allowance_(TXNService_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TXNService::Stub::Coin(::grpc::ClientContext* context, const ::zera_txn::CoinTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::CoinTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Coin_, context, request, response);
}

void TXNService::Stub::async::Coin(::grpc::ClientContext* context, const ::zera_txn::CoinTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::CoinTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Coin_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Coin(::grpc::ClientContext* context, const ::zera_txn::CoinTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Coin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncCoinRaw(::grpc::ClientContext* context, const ::zera_txn::CoinTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::CoinTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Coin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncCoinRaw(::grpc::ClientContext* context, const ::zera_txn::CoinTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCoinRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::Mint(::grpc::ClientContext* context, const ::zera_txn::MintTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::MintTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Mint_, context, request, response);
}

void TXNService::Stub::async::Mint(::grpc::ClientContext* context, const ::zera_txn::MintTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::MintTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mint_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Mint(::grpc::ClientContext* context, const ::zera_txn::MintTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Mint_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncMintRaw(::grpc::ClientContext* context, const ::zera_txn::MintTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::MintTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Mint_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncMintRaw(::grpc::ClientContext* context, const ::zera_txn::MintTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMintRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::ItemMint(::grpc::ClientContext* context, const ::zera_txn::ItemizedMintTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::ItemizedMintTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ItemMint_, context, request, response);
}

void TXNService::Stub::async::ItemMint(::grpc::ClientContext* context, const ::zera_txn::ItemizedMintTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::ItemizedMintTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ItemMint_, context, request, response, std::move(f));
}

void TXNService::Stub::async::ItemMint(::grpc::ClientContext* context, const ::zera_txn::ItemizedMintTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ItemMint_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncItemMintRaw(::grpc::ClientContext* context, const ::zera_txn::ItemizedMintTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::ItemizedMintTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ItemMint_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncItemMintRaw(::grpc::ClientContext* context, const ::zera_txn::ItemizedMintTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncItemMintRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::Contract(::grpc::ClientContext* context, const ::zera_txn::InstrumentContract& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::InstrumentContract, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Contract_, context, request, response);
}

void TXNService::Stub::async::Contract(::grpc::ClientContext* context, const ::zera_txn::InstrumentContract* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::InstrumentContract, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Contract_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Contract(::grpc::ClientContext* context, const ::zera_txn::InstrumentContract* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Contract_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncContractRaw(::grpc::ClientContext* context, const ::zera_txn::InstrumentContract& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::InstrumentContract, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Contract_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncContractRaw(::grpc::ClientContext* context, const ::zera_txn::InstrumentContract& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncContractRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::GovernProposal(::grpc::ClientContext* context, const ::zera_txn::GovernanceProposal& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::GovernanceProposal, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GovernProposal_, context, request, response);
}

void TXNService::Stub::async::GovernProposal(::grpc::ClientContext* context, const ::zera_txn::GovernanceProposal* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::GovernanceProposal, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GovernProposal_, context, request, response, std::move(f));
}

void TXNService::Stub::async::GovernProposal(::grpc::ClientContext* context, const ::zera_txn::GovernanceProposal* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GovernProposal_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncGovernProposalRaw(::grpc::ClientContext* context, const ::zera_txn::GovernanceProposal& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::GovernanceProposal, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GovernProposal_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncGovernProposalRaw(::grpc::ClientContext* context, const ::zera_txn::GovernanceProposal& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGovernProposalRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::GovernVote(::grpc::ClientContext* context, const ::zera_txn::GovernanceVote& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::GovernanceVote, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GovernVote_, context, request, response);
}

void TXNService::Stub::async::GovernVote(::grpc::ClientContext* context, const ::zera_txn::GovernanceVote* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::GovernanceVote, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GovernVote_, context, request, response, std::move(f));
}

void TXNService::Stub::async::GovernVote(::grpc::ClientContext* context, const ::zera_txn::GovernanceVote* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GovernVote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncGovernVoteRaw(::grpc::ClientContext* context, const ::zera_txn::GovernanceVote& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::GovernanceVote, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GovernVote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncGovernVoteRaw(::grpc::ClientContext* context, const ::zera_txn::GovernanceVote& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGovernVoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::SmartContract(::grpc::ClientContext* context, const ::zera_txn::SmartContractTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::SmartContractTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SmartContract_, context, request, response);
}

void TXNService::Stub::async::SmartContract(::grpc::ClientContext* context, const ::zera_txn::SmartContractTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::SmartContractTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContract_, context, request, response, std::move(f));
}

void TXNService::Stub::async::SmartContract(::grpc::ClientContext* context, const ::zera_txn::SmartContractTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContract_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncSmartContractRaw(::grpc::ClientContext* context, const ::zera_txn::SmartContractTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::SmartContractTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SmartContract_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncSmartContractRaw(::grpc::ClientContext* context, const ::zera_txn::SmartContractTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSmartContractRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::SmartContractExecute(::grpc::ClientContext* context, const ::zera_txn::SmartContractExecuteTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::SmartContractExecuteTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SmartContractExecute_, context, request, response);
}

void TXNService::Stub::async::SmartContractExecute(::grpc::ClientContext* context, const ::zera_txn::SmartContractExecuteTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::SmartContractExecuteTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractExecute_, context, request, response, std::move(f));
}

void TXNService::Stub::async::SmartContractExecute(::grpc::ClientContext* context, const ::zera_txn::SmartContractExecuteTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractExecute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncSmartContractExecuteRaw(::grpc::ClientContext* context, const ::zera_txn::SmartContractExecuteTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::SmartContractExecuteTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SmartContractExecute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncSmartContractExecuteRaw(::grpc::ClientContext* context, const ::zera_txn::SmartContractExecuteTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSmartContractExecuteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::SmartContractInstantiate(::grpc::ClientContext* context, const ::zera_txn::SmartContractInstantiateTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::SmartContractInstantiateTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SmartContractInstantiate_, context, request, response);
}

void TXNService::Stub::async::SmartContractInstantiate(::grpc::ClientContext* context, const ::zera_txn::SmartContractInstantiateTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::SmartContractInstantiateTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractInstantiate_, context, request, response, std::move(f));
}

void TXNService::Stub::async::SmartContractInstantiate(::grpc::ClientContext* context, const ::zera_txn::SmartContractInstantiateTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractInstantiate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncSmartContractInstantiateRaw(::grpc::ClientContext* context, const ::zera_txn::SmartContractInstantiateTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::SmartContractInstantiateTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SmartContractInstantiate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncSmartContractInstantiateRaw(::grpc::ClientContext* context, const ::zera_txn::SmartContractInstantiateTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSmartContractInstantiateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::CurrencyEquiv(::grpc::ClientContext* context, const ::zera_txn::SelfCurrencyEquiv& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::SelfCurrencyEquiv, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CurrencyEquiv_, context, request, response);
}

void TXNService::Stub::async::CurrencyEquiv(::grpc::ClientContext* context, const ::zera_txn::SelfCurrencyEquiv* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::SelfCurrencyEquiv, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CurrencyEquiv_, context, request, response, std::move(f));
}

void TXNService::Stub::async::CurrencyEquiv(::grpc::ClientContext* context, const ::zera_txn::SelfCurrencyEquiv* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CurrencyEquiv_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncCurrencyEquivRaw(::grpc::ClientContext* context, const ::zera_txn::SelfCurrencyEquiv& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::SelfCurrencyEquiv, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CurrencyEquiv_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncCurrencyEquivRaw(::grpc::ClientContext* context, const ::zera_txn::SelfCurrencyEquiv& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCurrencyEquivRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::AuthCurrencyEquiv(::grpc::ClientContext* context, const ::zera_txn::AuthorizedCurrencyEquiv& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::AuthorizedCurrencyEquiv, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AuthCurrencyEquiv_, context, request, response);
}

void TXNService::Stub::async::AuthCurrencyEquiv(::grpc::ClientContext* context, const ::zera_txn::AuthorizedCurrencyEquiv* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::AuthorizedCurrencyEquiv, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthCurrencyEquiv_, context, request, response, std::move(f));
}

void TXNService::Stub::async::AuthCurrencyEquiv(::grpc::ClientContext* context, const ::zera_txn::AuthorizedCurrencyEquiv* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthCurrencyEquiv_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncAuthCurrencyEquivRaw(::grpc::ClientContext* context, const ::zera_txn::AuthorizedCurrencyEquiv& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::AuthorizedCurrencyEquiv, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AuthCurrencyEquiv_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncAuthCurrencyEquivRaw(::grpc::ClientContext* context, const ::zera_txn::AuthorizedCurrencyEquiv& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAuthCurrencyEquivRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::ExpenseRatio(::grpc::ClientContext* context, const ::zera_txn::ExpenseRatioTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::ExpenseRatioTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExpenseRatio_, context, request, response);
}

void TXNService::Stub::async::ExpenseRatio(::grpc::ClientContext* context, const ::zera_txn::ExpenseRatioTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::ExpenseRatioTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExpenseRatio_, context, request, response, std::move(f));
}

void TXNService::Stub::async::ExpenseRatio(::grpc::ClientContext* context, const ::zera_txn::ExpenseRatioTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExpenseRatio_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncExpenseRatioRaw(::grpc::ClientContext* context, const ::zera_txn::ExpenseRatioTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::ExpenseRatioTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExpenseRatio_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncExpenseRatioRaw(::grpc::ClientContext* context, const ::zera_txn::ExpenseRatioTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExpenseRatioRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::NFT(::grpc::ClientContext* context, const ::zera_txn::NFTTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::NFTTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NFT_, context, request, response);
}

void TXNService::Stub::async::NFT(::grpc::ClientContext* context, const ::zera_txn::NFTTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::NFTTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NFT_, context, request, response, std::move(f));
}

void TXNService::Stub::async::NFT(::grpc::ClientContext* context, const ::zera_txn::NFTTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NFT_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncNFTRaw(::grpc::ClientContext* context, const ::zera_txn::NFTTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::NFTTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NFT_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncNFTRaw(::grpc::ClientContext* context, const ::zera_txn::NFTTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNFTRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::ContractUpdate(::grpc::ClientContext* context, const ::zera_txn::ContractUpdateTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::ContractUpdateTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ContractUpdate_, context, request, response);
}

void TXNService::Stub::async::ContractUpdate(::grpc::ClientContext* context, const ::zera_txn::ContractUpdateTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::ContractUpdateTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ContractUpdate_, context, request, response, std::move(f));
}

void TXNService::Stub::async::ContractUpdate(::grpc::ClientContext* context, const ::zera_txn::ContractUpdateTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ContractUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncContractUpdateRaw(::grpc::ClientContext* context, const ::zera_txn::ContractUpdateTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::ContractUpdateTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ContractUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncContractUpdateRaw(::grpc::ClientContext* context, const ::zera_txn::ContractUpdateTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncContractUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::Foundation(::grpc::ClientContext* context, const ::zera_txn::FoundationTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::FoundationTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Foundation_, context, request, response);
}

void TXNService::Stub::async::Foundation(::grpc::ClientContext* context, const ::zera_txn::FoundationTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::FoundationTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Foundation_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Foundation(::grpc::ClientContext* context, const ::zera_txn::FoundationTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Foundation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncFoundationRaw(::grpc::ClientContext* context, const ::zera_txn::FoundationTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::FoundationTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Foundation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncFoundationRaw(::grpc::ClientContext* context, const ::zera_txn::FoundationTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFoundationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::DelegatedVoting(::grpc::ClientContext* context, const ::zera_txn::DelegatedTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::DelegatedTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DelegatedVoting_, context, request, response);
}

void TXNService::Stub::async::DelegatedVoting(::grpc::ClientContext* context, const ::zera_txn::DelegatedTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::DelegatedTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelegatedVoting_, context, request, response, std::move(f));
}

void TXNService::Stub::async::DelegatedVoting(::grpc::ClientContext* context, const ::zera_txn::DelegatedTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelegatedVoting_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncDelegatedVotingRaw(::grpc::ClientContext* context, const ::zera_txn::DelegatedTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::DelegatedTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DelegatedVoting_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncDelegatedVotingRaw(::grpc::ClientContext* context, const ::zera_txn::DelegatedTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDelegatedVotingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::Quash(::grpc::ClientContext* context, const ::zera_txn::QuashTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::QuashTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Quash_, context, request, response);
}

void TXNService::Stub::async::Quash(::grpc::ClientContext* context, const ::zera_txn::QuashTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::QuashTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Quash_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Quash(::grpc::ClientContext* context, const ::zera_txn::QuashTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Quash_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncQuashRaw(::grpc::ClientContext* context, const ::zera_txn::QuashTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::QuashTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Quash_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncQuashRaw(::grpc::ClientContext* context, const ::zera_txn::QuashTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQuashRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::FastQuorum(::grpc::ClientContext* context, const ::zera_txn::FastQuorumTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::FastQuorumTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FastQuorum_, context, request, response);
}

void TXNService::Stub::async::FastQuorum(::grpc::ClientContext* context, const ::zera_txn::FastQuorumTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::FastQuorumTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FastQuorum_, context, request, response, std::move(f));
}

void TXNService::Stub::async::FastQuorum(::grpc::ClientContext* context, const ::zera_txn::FastQuorumTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FastQuorum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncFastQuorumRaw(::grpc::ClientContext* context, const ::zera_txn::FastQuorumTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::FastQuorumTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FastQuorum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncFastQuorumRaw(::grpc::ClientContext* context, const ::zera_txn::FastQuorumTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFastQuorumRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::Revoke(::grpc::ClientContext* context, const ::zera_txn::RevokeTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::RevokeTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Revoke_, context, request, response);
}

void TXNService::Stub::async::Revoke(::grpc::ClientContext* context, const ::zera_txn::RevokeTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::RevokeTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Revoke_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Revoke(::grpc::ClientContext* context, const ::zera_txn::RevokeTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Revoke_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncRevokeRaw(::grpc::ClientContext* context, const ::zera_txn::RevokeTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::RevokeTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Revoke_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncRevokeRaw(::grpc::ClientContext* context, const ::zera_txn::RevokeTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRevokeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::Compliance(::grpc::ClientContext* context, const ::zera_txn::ComplianceTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::ComplianceTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Compliance_, context, request, response);
}

void TXNService::Stub::async::Compliance(::grpc::ClientContext* context, const ::zera_txn::ComplianceTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::ComplianceTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Compliance_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Compliance(::grpc::ClientContext* context, const ::zera_txn::ComplianceTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Compliance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncComplianceRaw(::grpc::ClientContext* context, const ::zera_txn::ComplianceTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::ComplianceTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Compliance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncComplianceRaw(::grpc::ClientContext* context, const ::zera_txn::ComplianceTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncComplianceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::BurnSBT(::grpc::ClientContext* context, const ::zera_txn::BurnSBTTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::BurnSBTTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BurnSBT_, context, request, response);
}

void TXNService::Stub::async::BurnSBT(::grpc::ClientContext* context, const ::zera_txn::BurnSBTTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::BurnSBTTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BurnSBT_, context, request, response, std::move(f));
}

void TXNService::Stub::async::BurnSBT(::grpc::ClientContext* context, const ::zera_txn::BurnSBTTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BurnSBT_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncBurnSBTRaw(::grpc::ClientContext* context, const ::zera_txn::BurnSBTTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::BurnSBTTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BurnSBT_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncBurnSBTRaw(::grpc::ClientContext* context, const ::zera_txn::BurnSBTTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBurnSBTRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TXNService::Stub::Allowance(::grpc::ClientContext* context, const ::zera_txn::AllowanceTXN& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_txn::AllowanceTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Allowance_, context, request, response);
}

void TXNService::Stub::async::Allowance(::grpc::ClientContext* context, const ::zera_txn::AllowanceTXN* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_txn::AllowanceTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Allowance_, context, request, response, std::move(f));
}

void TXNService::Stub::async::Allowance(::grpc::ClientContext* context, const ::zera_txn::AllowanceTXN* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Allowance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::PrepareAsyncAllowanceRaw(::grpc::ClientContext* context, const ::zera_txn::AllowanceTXN& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_txn::AllowanceTXN, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Allowance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* TXNService::Stub::AsyncAllowanceRaw(::grpc::ClientContext* context, const ::zera_txn::AllowanceTXN& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAllowanceRaw(context, request, cq);
  result->StartCall();
  return result;
}

TXNService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::CoinTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::CoinTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->Coin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::MintTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::MintTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->Mint(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::ItemizedMintTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::ItemizedMintTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->ItemMint(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::InstrumentContract, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::InstrumentContract* req,
             ::google::protobuf::Empty* resp) {
               return service->Contract(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::GovernanceProposal, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::GovernanceProposal* req,
             ::google::protobuf::Empty* resp) {
               return service->GovernProposal(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::GovernanceVote, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::GovernanceVote* req,
             ::google::protobuf::Empty* resp) {
               return service->GovernVote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::SmartContractTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::SmartContractTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->SmartContract(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::SmartContractExecuteTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::SmartContractExecuteTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->SmartContractExecute(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::SmartContractInstantiateTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::SmartContractInstantiateTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->SmartContractInstantiate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::SelfCurrencyEquiv, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::SelfCurrencyEquiv* req,
             ::google::protobuf::Empty* resp) {
               return service->CurrencyEquiv(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::AuthorizedCurrencyEquiv, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::AuthorizedCurrencyEquiv* req,
             ::google::protobuf::Empty* resp) {
               return service->AuthCurrencyEquiv(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::ExpenseRatioTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::ExpenseRatioTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->ExpenseRatio(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::NFTTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::NFTTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->NFT(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::ContractUpdateTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::ContractUpdateTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->ContractUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::FoundationTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::FoundationTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->Foundation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::DelegatedTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::DelegatedTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->DelegatedVoting(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::QuashTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::QuashTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->Quash(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::FastQuorumTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::FastQuorumTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->FastQuorum(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::RevokeTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::RevokeTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->Revoke(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::ComplianceTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::ComplianceTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->Compliance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::BurnSBTTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::BurnSBTTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->BurnSBT(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TXNService_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TXNService::Service, ::zera_txn::AllowanceTXN, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TXNService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_txn::AllowanceTXN* req,
             ::google::protobuf::Empty* resp) {
               return service->Allowance(ctx, req, resp);
             }, this)));
}

TXNService::Service::~Service() {
}

::grpc::Status TXNService::Service::Coin(::grpc::ServerContext* context, const ::zera_txn::CoinTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::Mint(::grpc::ServerContext* context, const ::zera_txn::MintTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::ItemMint(::grpc::ServerContext* context, const ::zera_txn::ItemizedMintTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::Contract(::grpc::ServerContext* context, const ::zera_txn::InstrumentContract* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::GovernProposal(::grpc::ServerContext* context, const ::zera_txn::GovernanceProposal* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::GovernVote(::grpc::ServerContext* context, const ::zera_txn::GovernanceVote* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::SmartContract(::grpc::ServerContext* context, const ::zera_txn::SmartContractTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::SmartContractExecute(::grpc::ServerContext* context, const ::zera_txn::SmartContractExecuteTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::SmartContractInstantiate(::grpc::ServerContext* context, const ::zera_txn::SmartContractInstantiateTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::CurrencyEquiv(::grpc::ServerContext* context, const ::zera_txn::SelfCurrencyEquiv* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::AuthCurrencyEquiv(::grpc::ServerContext* context, const ::zera_txn::AuthorizedCurrencyEquiv* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::ExpenseRatio(::grpc::ServerContext* context, const ::zera_txn::ExpenseRatioTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::NFT(::grpc::ServerContext* context, const ::zera_txn::NFTTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::ContractUpdate(::grpc::ServerContext* context, const ::zera_txn::ContractUpdateTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::Foundation(::grpc::ServerContext* context, const ::zera_txn::FoundationTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::DelegatedVoting(::grpc::ServerContext* context, const ::zera_txn::DelegatedTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::Quash(::grpc::ServerContext* context, const ::zera_txn::QuashTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::FastQuorum(::grpc::ServerContext* context, const ::zera_txn::FastQuorumTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::Revoke(::grpc::ServerContext* context, const ::zera_txn::RevokeTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::Compliance(::grpc::ServerContext* context, const ::zera_txn::ComplianceTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::BurnSBT(::grpc::ServerContext* context, const ::zera_txn::BurnSBTTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TXNService::Service::Allowance(::grpc::ServerContext* context, const ::zera_txn::AllowanceTXN* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace zera_txn

