// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

#include "wallet.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_txn_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MaxSupplyRelease_txn_2eproto;
namespace zera_wallets {
class MaxSupplyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MaxSupply> _instance;
} _MaxSupply_default_instance_;
}  // namespace zera_wallets
static void InitDefaultsscc_info_MaxSupply_wallet_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::zera_wallets::_MaxSupply_default_instance_;
    new (ptr) ::zera_wallets::MaxSupply();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zera_wallets::MaxSupply::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_MaxSupply_wallet_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_MaxSupply_wallet_2eproto}, {
      &scc_info_MaxSupplyRelease_txn_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_wallet_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_wallet_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_wallet_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_wallet_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::zera_wallets::MaxSupply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::zera_wallets::MaxSupply, max_supply_),
  PROTOBUF_FIELD_OFFSET(::zera_wallets::MaxSupply, circulation_),
  PROTOBUF_FIELD_OFFSET(::zera_wallets::MaxSupply, release_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::zera_wallets::MaxSupply)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::zera_wallets::_MaxSupply_default_instance_),
};

const char descriptor_table_protodef_wallet_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014wallet.proto\022\014zera_wallets\032\ttxn.proto\""
  "a\n\tMaxSupply\022\022\n\nmax_supply\030\001 \001(\t\022\023\n\013circ"
  "ulation\030\002 \001(\t\022+\n\007release\030\003 \003(\0132\032.zera_tx"
  "n.MaxSupplyReleaseB\002H\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_wallet_2eproto_deps[1] = {
  &::descriptor_table_txn_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_wallet_2eproto_sccs[1] = {
  &scc_info_MaxSupply_wallet_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_wallet_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wallet_2eproto = {
  false, false, descriptor_table_protodef_wallet_2eproto, "wallet.proto", 150,
  &descriptor_table_wallet_2eproto_once, descriptor_table_wallet_2eproto_sccs, descriptor_table_wallet_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_wallet_2eproto::offsets,
  file_level_metadata_wallet_2eproto, 1, file_level_enum_descriptors_wallet_2eproto, file_level_service_descriptors_wallet_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_wallet_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_wallet_2eproto)), true);
namespace zera_wallets {

// ===================================================================

void MaxSupply::InitAsDefaultInstance() {
}
class MaxSupply::_Internal {
 public:
};

void MaxSupply::clear_release() {
  release_.Clear();
}
MaxSupply::MaxSupply(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  release_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:zera_wallets.MaxSupply)
}
MaxSupply::MaxSupply(const MaxSupply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      release_(from.release_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  max_supply_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_max_supply().empty()) {
    max_supply_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_max_supply(),
      GetArena());
  }
  circulation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_circulation().empty()) {
    circulation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_circulation(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:zera_wallets.MaxSupply)
}

void MaxSupply::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MaxSupply_wallet_2eproto.base);
  max_supply_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  circulation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

MaxSupply::~MaxSupply() {
  // @@protoc_insertion_point(destructor:zera_wallets.MaxSupply)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MaxSupply::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  max_supply_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  circulation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void MaxSupply::ArenaDtor(void* object) {
  MaxSupply* _this = reinterpret_cast< MaxSupply* >(object);
  (void)_this;
}
void MaxSupply::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MaxSupply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MaxSupply& MaxSupply::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MaxSupply_wallet_2eproto.base);
  return *internal_default_instance();
}


void MaxSupply::Clear() {
// @@protoc_insertion_point(message_clear_start:zera_wallets.MaxSupply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  release_.Clear();
  max_supply_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  circulation_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MaxSupply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string max_supply = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_max_supply();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "zera_wallets.MaxSupply.max_supply"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string circulation = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_circulation();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "zera_wallets.MaxSupply.circulation"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .zera_txn.MaxSupplyRelease release = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_release(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MaxSupply::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:zera_wallets.MaxSupply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string max_supply = 1;
  if (this->max_supply().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_max_supply().data(), static_cast<int>(this->_internal_max_supply().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "zera_wallets.MaxSupply.max_supply");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_max_supply(), target);
  }

  // string circulation = 2;
  if (this->circulation().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_circulation().data(), static_cast<int>(this->_internal_circulation().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "zera_wallets.MaxSupply.circulation");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_circulation(), target);
  }

  // repeated .zera_txn.MaxSupplyRelease release = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_release_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_release(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zera_wallets.MaxSupply)
  return target;
}

size_t MaxSupply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zera_wallets.MaxSupply)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .zera_txn.MaxSupplyRelease release = 3;
  total_size += 1UL * this->_internal_release_size();
  for (const auto& msg : this->release_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string max_supply = 1;
  if (this->max_supply().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_max_supply());
  }

  // string circulation = 2;
  if (this->circulation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_circulation());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MaxSupply::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:zera_wallets.MaxSupply)
  GOOGLE_DCHECK_NE(&from, this);
  const MaxSupply* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MaxSupply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:zera_wallets.MaxSupply)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:zera_wallets.MaxSupply)
    MergeFrom(*source);
  }
}

void MaxSupply::MergeFrom(const MaxSupply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:zera_wallets.MaxSupply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  release_.MergeFrom(from.release_);
  if (from.max_supply().size() > 0) {
    _internal_set_max_supply(from._internal_max_supply());
  }
  if (from.circulation().size() > 0) {
    _internal_set_circulation(from._internal_circulation());
  }
}

void MaxSupply::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:zera_wallets.MaxSupply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MaxSupply::CopyFrom(const MaxSupply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zera_wallets.MaxSupply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MaxSupply::IsInitialized() const {
  return true;
}

void MaxSupply::InternalSwap(MaxSupply* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  release_.InternalSwap(&other->release_);
  max_supply_.Swap(&other->max_supply_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  circulation_.Swap(&other->circulation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata MaxSupply::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace zera_wallets
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::zera_wallets::MaxSupply* Arena::CreateMaybeMessage< ::zera_wallets::MaxSupply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::zera_wallets::MaxSupply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
