// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wallet_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wallet_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "txn.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wallet_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_wallet_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wallet_2eproto;
namespace zera_wallets {
class MaxSupply;
class MaxSupplyDefaultTypeInternal;
extern MaxSupplyDefaultTypeInternal _MaxSupply_default_instance_;
}  // namespace zera_wallets
PROTOBUF_NAMESPACE_OPEN
template<> ::zera_wallets::MaxSupply* Arena::CreateMaybeMessage<::zera_wallets::MaxSupply>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace zera_wallets {

// ===================================================================

class MaxSupply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:zera_wallets.MaxSupply) */ {
 public:
  inline MaxSupply() : MaxSupply(nullptr) {};
  virtual ~MaxSupply();

  MaxSupply(const MaxSupply& from);
  MaxSupply(MaxSupply&& from) noexcept
    : MaxSupply() {
    *this = ::std::move(from);
  }

  inline MaxSupply& operator=(const MaxSupply& from) {
    CopyFrom(from);
    return *this;
  }
  inline MaxSupply& operator=(MaxSupply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MaxSupply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MaxSupply* internal_default_instance() {
    return reinterpret_cast<const MaxSupply*>(
               &_MaxSupply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MaxSupply& a, MaxSupply& b) {
    a.Swap(&b);
  }
  inline void Swap(MaxSupply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MaxSupply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MaxSupply* New() const final {
    return CreateMaybeMessage<MaxSupply>(nullptr);
  }

  MaxSupply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MaxSupply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MaxSupply& from);
  void MergeFrom(const MaxSupply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MaxSupply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "zera_wallets.MaxSupply";
  }
  protected:
  explicit MaxSupply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_wallet_2eproto);
    return ::descriptor_table_wallet_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReleaseFieldNumber = 3,
    kMaxSupplyFieldNumber = 1,
    kCirculationFieldNumber = 2,
  };
  // repeated .zera_txn.MaxSupplyRelease release = 3;
  int release_size() const;
  private:
  int _internal_release_size() const;
  public:
  void clear_release();
  ::zera_txn::MaxSupplyRelease* mutable_release(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zera_txn::MaxSupplyRelease >*
      mutable_release();
  private:
  const ::zera_txn::MaxSupplyRelease& _internal_release(int index) const;
  ::zera_txn::MaxSupplyRelease* _internal_add_release();
  public:
  const ::zera_txn::MaxSupplyRelease& release(int index) const;
  ::zera_txn::MaxSupplyRelease* add_release();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zera_txn::MaxSupplyRelease >&
      release() const;

  // string max_supply = 1;
  void clear_max_supply();
  const std::string& max_supply() const;
  void set_max_supply(const std::string& value);
  void set_max_supply(std::string&& value);
  void set_max_supply(const char* value);
  void set_max_supply(const char* value, size_t size);
  std::string* mutable_max_supply();
  std::string* release_max_supply();
  void set_allocated_max_supply(std::string* max_supply);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_max_supply();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_max_supply(
      std::string* max_supply);
  private:
  const std::string& _internal_max_supply() const;
  void _internal_set_max_supply(const std::string& value);
  std::string* _internal_mutable_max_supply();
  public:

  // string circulation = 2;
  void clear_circulation();
  const std::string& circulation() const;
  void set_circulation(const std::string& value);
  void set_circulation(std::string&& value);
  void set_circulation(const char* value);
  void set_circulation(const char* value, size_t size);
  std::string* mutable_circulation();
  std::string* release_circulation();
  void set_allocated_circulation(std::string* circulation);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_circulation();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_circulation(
      std::string* circulation);
  private:
  const std::string& _internal_circulation() const;
  void _internal_set_circulation(const std::string& value);
  std::string* _internal_mutable_circulation();
  public:

  // @@protoc_insertion_point(class_scope:zera_wallets.MaxSupply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zera_txn::MaxSupplyRelease > release_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr max_supply_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr circulation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wallet_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MaxSupply

// string max_supply = 1;
inline void MaxSupply::clear_max_supply() {
  max_supply_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MaxSupply::max_supply() const {
  // @@protoc_insertion_point(field_get:zera_wallets.MaxSupply.max_supply)
  return _internal_max_supply();
}
inline void MaxSupply::set_max_supply(const std::string& value) {
  _internal_set_max_supply(value);
  // @@protoc_insertion_point(field_set:zera_wallets.MaxSupply.max_supply)
}
inline std::string* MaxSupply::mutable_max_supply() {
  // @@protoc_insertion_point(field_mutable:zera_wallets.MaxSupply.max_supply)
  return _internal_mutable_max_supply();
}
inline const std::string& MaxSupply::_internal_max_supply() const {
  return max_supply_.Get();
}
inline void MaxSupply::_internal_set_max_supply(const std::string& value) {
  
  max_supply_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MaxSupply::set_max_supply(std::string&& value) {
  
  max_supply_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:zera_wallets.MaxSupply.max_supply)
}
inline void MaxSupply::set_max_supply(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  max_supply_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:zera_wallets.MaxSupply.max_supply)
}
inline void MaxSupply::set_max_supply(const char* value,
    size_t size) {
  
  max_supply_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:zera_wallets.MaxSupply.max_supply)
}
inline std::string* MaxSupply::_internal_mutable_max_supply() {
  
  return max_supply_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MaxSupply::release_max_supply() {
  // @@protoc_insertion_point(field_release:zera_wallets.MaxSupply.max_supply)
  return max_supply_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MaxSupply::set_allocated_max_supply(std::string* max_supply) {
  if (max_supply != nullptr) {
    
  } else {
    
  }
  max_supply_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), max_supply,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:zera_wallets.MaxSupply.max_supply)
}
inline std::string* MaxSupply::unsafe_arena_release_max_supply() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zera_wallets.MaxSupply.max_supply)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return max_supply_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void MaxSupply::unsafe_arena_set_allocated_max_supply(
    std::string* max_supply) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (max_supply != nullptr) {
    
  } else {
    
  }
  max_supply_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      max_supply, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zera_wallets.MaxSupply.max_supply)
}

// string circulation = 2;
inline void MaxSupply::clear_circulation() {
  circulation_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MaxSupply::circulation() const {
  // @@protoc_insertion_point(field_get:zera_wallets.MaxSupply.circulation)
  return _internal_circulation();
}
inline void MaxSupply::set_circulation(const std::string& value) {
  _internal_set_circulation(value);
  // @@protoc_insertion_point(field_set:zera_wallets.MaxSupply.circulation)
}
inline std::string* MaxSupply::mutable_circulation() {
  // @@protoc_insertion_point(field_mutable:zera_wallets.MaxSupply.circulation)
  return _internal_mutable_circulation();
}
inline const std::string& MaxSupply::_internal_circulation() const {
  return circulation_.Get();
}
inline void MaxSupply::_internal_set_circulation(const std::string& value) {
  
  circulation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MaxSupply::set_circulation(std::string&& value) {
  
  circulation_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:zera_wallets.MaxSupply.circulation)
}
inline void MaxSupply::set_circulation(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  circulation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:zera_wallets.MaxSupply.circulation)
}
inline void MaxSupply::set_circulation(const char* value,
    size_t size) {
  
  circulation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:zera_wallets.MaxSupply.circulation)
}
inline std::string* MaxSupply::_internal_mutable_circulation() {
  
  return circulation_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MaxSupply::release_circulation() {
  // @@protoc_insertion_point(field_release:zera_wallets.MaxSupply.circulation)
  return circulation_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MaxSupply::set_allocated_circulation(std::string* circulation) {
  if (circulation != nullptr) {
    
  } else {
    
  }
  circulation_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), circulation,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:zera_wallets.MaxSupply.circulation)
}
inline std::string* MaxSupply::unsafe_arena_release_circulation() {
  // @@protoc_insertion_point(field_unsafe_arena_release:zera_wallets.MaxSupply.circulation)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return circulation_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void MaxSupply::unsafe_arena_set_allocated_circulation(
    std::string* circulation) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (circulation != nullptr) {
    
  } else {
    
  }
  circulation_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      circulation, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:zera_wallets.MaxSupply.circulation)
}

// repeated .zera_txn.MaxSupplyRelease release = 3;
inline int MaxSupply::_internal_release_size() const {
  return release_.size();
}
inline int MaxSupply::release_size() const {
  return _internal_release_size();
}
inline ::zera_txn::MaxSupplyRelease* MaxSupply::mutable_release(int index) {
  // @@protoc_insertion_point(field_mutable:zera_wallets.MaxSupply.release)
  return release_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zera_txn::MaxSupplyRelease >*
MaxSupply::mutable_release() {
  // @@protoc_insertion_point(field_mutable_list:zera_wallets.MaxSupply.release)
  return &release_;
}
inline const ::zera_txn::MaxSupplyRelease& MaxSupply::_internal_release(int index) const {
  return release_.Get(index);
}
inline const ::zera_txn::MaxSupplyRelease& MaxSupply::release(int index) const {
  // @@protoc_insertion_point(field_get:zera_wallets.MaxSupply.release)
  return _internal_release(index);
}
inline ::zera_txn::MaxSupplyRelease* MaxSupply::_internal_add_release() {
  return release_.Add();
}
inline ::zera_txn::MaxSupplyRelease* MaxSupply::add_release() {
  // @@protoc_insertion_point(field_add:zera_wallets.MaxSupply.release)
  return _internal_add_release();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::zera_txn::MaxSupplyRelease >&
MaxSupply::release() const {
  // @@protoc_insertion_point(field_list:zera_wallets.MaxSupply.release)
  return release_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace zera_wallets

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wallet_2eproto
