// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: zera_api.proto

#include "zera_api.pb.h"
#include "zera_api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace zera_api {

static const char* APIService_method_names[] = {
  "/zera_api.APIService/Balance",
  "/zera_api.APIService/Nonce",
  "/zera_api.APIService/ContractFee",
  "/zera_api.APIService/BaseFee",
  "/zera_api.APIService/GetTokenFeeInfo",
  "/zera_api.APIService/Items",
  "/zera_api.APIService/Denomination",
  "/zera_api.APIService/Database",
  "/zera_api.APIService/Block",
  "/zera_api.APIService/ProposalLedger",
  "/zera_api.APIService/SmartContractActivityRequest",
  "/zera_api.APIService/SmartContractEvents",
};

std::unique_ptr< APIService::Stub> APIService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< APIService::Stub> stub(new APIService::Stub(channel, options));
  return stub;
}

APIService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Balance_(APIService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Nonce_(APIService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ContractFee_(APIService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BaseFee_(APIService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTokenFeeInfo_(APIService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Items_(APIService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Denomination_(APIService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Database_(APIService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Block_(APIService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ProposalLedger_(APIService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SmartContractActivityRequest_(APIService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SmartContractEvents_(APIService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status APIService::Stub::Balance(::grpc::ClientContext* context, const ::zera_api::BalanceRequest& request, ::zera_api::BalanceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::BalanceRequest, ::zera_api::BalanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Balance_, context, request, response);
}

void APIService::Stub::async::Balance(::grpc::ClientContext* context, const ::zera_api::BalanceRequest* request, ::zera_api::BalanceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::BalanceRequest, ::zera_api::BalanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Balance_, context, request, response, std::move(f));
}

void APIService::Stub::async::Balance(::grpc::ClientContext* context, const ::zera_api::BalanceRequest* request, ::zera_api::BalanceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Balance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::BalanceResponse>* APIService::Stub::PrepareAsyncBalanceRaw(::grpc::ClientContext* context, const ::zera_api::BalanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::BalanceResponse, ::zera_api::BalanceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Balance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::BalanceResponse>* APIService::Stub::AsyncBalanceRaw(::grpc::ClientContext* context, const ::zera_api::BalanceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBalanceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::Nonce(::grpc::ClientContext* context, const ::zera_api::NonceRequest& request, ::zera_api::NonceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::NonceRequest, ::zera_api::NonceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Nonce_, context, request, response);
}

void APIService::Stub::async::Nonce(::grpc::ClientContext* context, const ::zera_api::NonceRequest* request, ::zera_api::NonceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::NonceRequest, ::zera_api::NonceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Nonce_, context, request, response, std::move(f));
}

void APIService::Stub::async::Nonce(::grpc::ClientContext* context, const ::zera_api::NonceRequest* request, ::zera_api::NonceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Nonce_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::NonceResponse>* APIService::Stub::PrepareAsyncNonceRaw(::grpc::ClientContext* context, const ::zera_api::NonceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::NonceResponse, ::zera_api::NonceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Nonce_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::NonceResponse>* APIService::Stub::AsyncNonceRaw(::grpc::ClientContext* context, const ::zera_api::NonceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNonceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::ContractFee(::grpc::ClientContext* context, const ::zera_api::ContractFeeRequest& request, ::zera_api::ContractFeeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::ContractFeeRequest, ::zera_api::ContractFeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ContractFee_, context, request, response);
}

void APIService::Stub::async::ContractFee(::grpc::ClientContext* context, const ::zera_api::ContractFeeRequest* request, ::zera_api::ContractFeeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::ContractFeeRequest, ::zera_api::ContractFeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ContractFee_, context, request, response, std::move(f));
}

void APIService::Stub::async::ContractFee(::grpc::ClientContext* context, const ::zera_api::ContractFeeRequest* request, ::zera_api::ContractFeeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ContractFee_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::ContractFeeResponse>* APIService::Stub::PrepareAsyncContractFeeRaw(::grpc::ClientContext* context, const ::zera_api::ContractFeeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::ContractFeeResponse, ::zera_api::ContractFeeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ContractFee_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::ContractFeeResponse>* APIService::Stub::AsyncContractFeeRaw(::grpc::ClientContext* context, const ::zera_api::ContractFeeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncContractFeeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::BaseFee(::grpc::ClientContext* context, const ::zera_api::BaseFeeRequest& request, ::zera_api::BaseFeeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::BaseFeeRequest, ::zera_api::BaseFeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BaseFee_, context, request, response);
}

void APIService::Stub::async::BaseFee(::grpc::ClientContext* context, const ::zera_api::BaseFeeRequest* request, ::zera_api::BaseFeeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::BaseFeeRequest, ::zera_api::BaseFeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BaseFee_, context, request, response, std::move(f));
}

void APIService::Stub::async::BaseFee(::grpc::ClientContext* context, const ::zera_api::BaseFeeRequest* request, ::zera_api::BaseFeeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BaseFee_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::BaseFeeResponse>* APIService::Stub::PrepareAsyncBaseFeeRaw(::grpc::ClientContext* context, const ::zera_api::BaseFeeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::BaseFeeResponse, ::zera_api::BaseFeeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BaseFee_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::BaseFeeResponse>* APIService::Stub::AsyncBaseFeeRaw(::grpc::ClientContext* context, const ::zera_api::BaseFeeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBaseFeeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::GetTokenFeeInfo(::grpc::ClientContext* context, const ::zera_api::TokenFeeInfoRequest& request, ::zera_api::TokenFeeInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::TokenFeeInfoRequest, ::zera_api::TokenFeeInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTokenFeeInfo_, context, request, response);
}

void APIService::Stub::async::GetTokenFeeInfo(::grpc::ClientContext* context, const ::zera_api::TokenFeeInfoRequest* request, ::zera_api::TokenFeeInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::TokenFeeInfoRequest, ::zera_api::TokenFeeInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTokenFeeInfo_, context, request, response, std::move(f));
}

void APIService::Stub::async::GetTokenFeeInfo(::grpc::ClientContext* context, const ::zera_api::TokenFeeInfoRequest* request, ::zera_api::TokenFeeInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTokenFeeInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::TokenFeeInfoResponse>* APIService::Stub::PrepareAsyncGetTokenFeeInfoRaw(::grpc::ClientContext* context, const ::zera_api::TokenFeeInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::TokenFeeInfoResponse, ::zera_api::TokenFeeInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTokenFeeInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::TokenFeeInfoResponse>* APIService::Stub::AsyncGetTokenFeeInfoRaw(::grpc::ClientContext* context, const ::zera_api::TokenFeeInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTokenFeeInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::Items(::grpc::ClientContext* context, const ::zera_api::ItemRequest& request, ::zera_api::ItemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::ItemRequest, ::zera_api::ItemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Items_, context, request, response);
}

void APIService::Stub::async::Items(::grpc::ClientContext* context, const ::zera_api::ItemRequest* request, ::zera_api::ItemResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::ItemRequest, ::zera_api::ItemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Items_, context, request, response, std::move(f));
}

void APIService::Stub::async::Items(::grpc::ClientContext* context, const ::zera_api::ItemRequest* request, ::zera_api::ItemResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Items_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::ItemResponse>* APIService::Stub::PrepareAsyncItemsRaw(::grpc::ClientContext* context, const ::zera_api::ItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::ItemResponse, ::zera_api::ItemRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Items_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::ItemResponse>* APIService::Stub::AsyncItemsRaw(::grpc::ClientContext* context, const ::zera_api::ItemRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncItemsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::Denomination(::grpc::ClientContext* context, const ::zera_api::DenominationRequest& request, ::zera_api::DenominationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::DenominationRequest, ::zera_api::DenominationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Denomination_, context, request, response);
}

void APIService::Stub::async::Denomination(::grpc::ClientContext* context, const ::zera_api::DenominationRequest* request, ::zera_api::DenominationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::DenominationRequest, ::zera_api::DenominationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Denomination_, context, request, response, std::move(f));
}

void APIService::Stub::async::Denomination(::grpc::ClientContext* context, const ::zera_api::DenominationRequest* request, ::zera_api::DenominationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Denomination_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::DenominationResponse>* APIService::Stub::PrepareAsyncDenominationRaw(::grpc::ClientContext* context, const ::zera_api::DenominationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::DenominationResponse, ::zera_api::DenominationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Denomination_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::DenominationResponse>* APIService::Stub::AsyncDenominationRaw(::grpc::ClientContext* context, const ::zera_api::DenominationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDenominationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::Database(::grpc::ClientContext* context, const ::zera_api::DatabaseRequest& request, ::zera_api::DatabaseResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::DatabaseRequest, ::zera_api::DatabaseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Database_, context, request, response);
}

void APIService::Stub::async::Database(::grpc::ClientContext* context, const ::zera_api::DatabaseRequest* request, ::zera_api::DatabaseResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::DatabaseRequest, ::zera_api::DatabaseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Database_, context, request, response, std::move(f));
}

void APIService::Stub::async::Database(::grpc::ClientContext* context, const ::zera_api::DatabaseRequest* request, ::zera_api::DatabaseResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Database_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::DatabaseResponse>* APIService::Stub::PrepareAsyncDatabaseRaw(::grpc::ClientContext* context, const ::zera_api::DatabaseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::DatabaseResponse, ::zera_api::DatabaseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Database_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::DatabaseResponse>* APIService::Stub::AsyncDatabaseRaw(::grpc::ClientContext* context, const ::zera_api::DatabaseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDatabaseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::Block(::grpc::ClientContext* context, const ::zera_api::BlockRequest& request, ::zera_api::BlockResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::BlockRequest, ::zera_api::BlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Block_, context, request, response);
}

void APIService::Stub::async::Block(::grpc::ClientContext* context, const ::zera_api::BlockRequest* request, ::zera_api::BlockResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::BlockRequest, ::zera_api::BlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Block_, context, request, response, std::move(f));
}

void APIService::Stub::async::Block(::grpc::ClientContext* context, const ::zera_api::BlockRequest* request, ::zera_api::BlockResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Block_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::BlockResponse>* APIService::Stub::PrepareAsyncBlockRaw(::grpc::ClientContext* context, const ::zera_api::BlockRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::BlockResponse, ::zera_api::BlockRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Block_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::BlockResponse>* APIService::Stub::AsyncBlockRaw(::grpc::ClientContext* context, const ::zera_api::BlockRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBlockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::ProposalLedger(::grpc::ClientContext* context, const ::zera_api::ProposalLedgerRequest& request, ::zera_api::ProposalLedgerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::ProposalLedgerRequest, ::zera_api::ProposalLedgerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProposalLedger_, context, request, response);
}

void APIService::Stub::async::ProposalLedger(::grpc::ClientContext* context, const ::zera_api::ProposalLedgerRequest* request, ::zera_api::ProposalLedgerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::ProposalLedgerRequest, ::zera_api::ProposalLedgerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProposalLedger_, context, request, response, std::move(f));
}

void APIService::Stub::async::ProposalLedger(::grpc::ClientContext* context, const ::zera_api::ProposalLedgerRequest* request, ::zera_api::ProposalLedgerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProposalLedger_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zera_api::ProposalLedgerResponse>* APIService::Stub::PrepareAsyncProposalLedgerRaw(::grpc::ClientContext* context, const ::zera_api::ProposalLedgerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zera_api::ProposalLedgerResponse, ::zera_api::ProposalLedgerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProposalLedger_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zera_api::ProposalLedgerResponse>* APIService::Stub::AsyncProposalLedgerRaw(::grpc::ClientContext* context, const ::zera_api::ProposalLedgerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProposalLedgerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::SmartContractActivityRequest(::grpc::ClientContext* context, const ::zera_api::ActivityRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::ActivityRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SmartContractActivityRequest_, context, request, response);
}

void APIService::Stub::async::SmartContractActivityRequest(::grpc::ClientContext* context, const ::zera_api::ActivityRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::ActivityRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractActivityRequest_, context, request, response, std::move(f));
}

void APIService::Stub::async::SmartContractActivityRequest(::grpc::ClientContext* context, const ::zera_api::ActivityRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractActivityRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* APIService::Stub::PrepareAsyncSmartContractActivityRequestRaw(::grpc::ClientContext* context, const ::zera_api::ActivityRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_api::ActivityRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SmartContractActivityRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* APIService::Stub::AsyncSmartContractActivityRequestRaw(::grpc::ClientContext* context, const ::zera_api::ActivityRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSmartContractActivityRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status APIService::Stub::SmartContractEvents(::grpc::ClientContext* context, const ::zera_api::SmartContractEventsResponse& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zera_api::SmartContractEventsResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SmartContractEvents_, context, request, response);
}

void APIService::Stub::async::SmartContractEvents(::grpc::ClientContext* context, const ::zera_api::SmartContractEventsResponse* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zera_api::SmartContractEventsResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractEvents_, context, request, response, std::move(f));
}

void APIService::Stub::async::SmartContractEvents(::grpc::ClientContext* context, const ::zera_api::SmartContractEventsResponse* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SmartContractEvents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* APIService::Stub::PrepareAsyncSmartContractEventsRaw(::grpc::ClientContext* context, const ::zera_api::SmartContractEventsResponse& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::zera_api::SmartContractEventsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SmartContractEvents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* APIService::Stub::AsyncSmartContractEventsRaw(::grpc::ClientContext* context, const ::zera_api::SmartContractEventsResponse& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSmartContractEventsRaw(context, request, cq);
  result->StartCall();
  return result;
}

APIService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::BalanceRequest, ::zera_api::BalanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::BalanceRequest* req,
             ::zera_api::BalanceResponse* resp) {
               return service->Balance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::NonceRequest, ::zera_api::NonceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::NonceRequest* req,
             ::zera_api::NonceResponse* resp) {
               return service->Nonce(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::ContractFeeRequest, ::zera_api::ContractFeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::ContractFeeRequest* req,
             ::zera_api::ContractFeeResponse* resp) {
               return service->ContractFee(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::BaseFeeRequest, ::zera_api::BaseFeeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::BaseFeeRequest* req,
             ::zera_api::BaseFeeResponse* resp) {
               return service->BaseFee(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::TokenFeeInfoRequest, ::zera_api::TokenFeeInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::TokenFeeInfoRequest* req,
             ::zera_api::TokenFeeInfoResponse* resp) {
               return service->GetTokenFeeInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::ItemRequest, ::zera_api::ItemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::ItemRequest* req,
             ::zera_api::ItemResponse* resp) {
               return service->Items(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::DenominationRequest, ::zera_api::DenominationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::DenominationRequest* req,
             ::zera_api::DenominationResponse* resp) {
               return service->Denomination(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::DatabaseRequest, ::zera_api::DatabaseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::DatabaseRequest* req,
             ::zera_api::DatabaseResponse* resp) {
               return service->Database(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::BlockRequest, ::zera_api::BlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::BlockRequest* req,
             ::zera_api::BlockResponse* resp) {
               return service->Block(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::ProposalLedgerRequest, ::zera_api::ProposalLedgerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::ProposalLedgerRequest* req,
             ::zera_api::ProposalLedgerResponse* resp) {
               return service->ProposalLedger(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::ActivityRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::ActivityRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->SmartContractActivityRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      APIService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< APIService::Service, ::zera_api::SmartContractEventsResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](APIService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zera_api::SmartContractEventsResponse* req,
             ::google::protobuf::Empty* resp) {
               return service->SmartContractEvents(ctx, req, resp);
             }, this)));
}

APIService::Service::~Service() {
}

::grpc::Status APIService::Service::Balance(::grpc::ServerContext* context, const ::zera_api::BalanceRequest* request, ::zera_api::BalanceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::Nonce(::grpc::ServerContext* context, const ::zera_api::NonceRequest* request, ::zera_api::NonceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::ContractFee(::grpc::ServerContext* context, const ::zera_api::ContractFeeRequest* request, ::zera_api::ContractFeeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::BaseFee(::grpc::ServerContext* context, const ::zera_api::BaseFeeRequest* request, ::zera_api::BaseFeeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::GetTokenFeeInfo(::grpc::ServerContext* context, const ::zera_api::TokenFeeInfoRequest* request, ::zera_api::TokenFeeInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::Items(::grpc::ServerContext* context, const ::zera_api::ItemRequest* request, ::zera_api::ItemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::Denomination(::grpc::ServerContext* context, const ::zera_api::DenominationRequest* request, ::zera_api::DenominationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::Database(::grpc::ServerContext* context, const ::zera_api::DatabaseRequest* request, ::zera_api::DatabaseResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::Block(::grpc::ServerContext* context, const ::zera_api::BlockRequest* request, ::zera_api::BlockResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::ProposalLedger(::grpc::ServerContext* context, const ::zera_api::ProposalLedgerRequest* request, ::zera_api::ProposalLedgerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::SmartContractActivityRequest(::grpc::ServerContext* context, const ::zera_api::ActivityRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status APIService::Service::SmartContractEvents(::grpc::ServerContext* context, const ::zera_api::SmartContractEventsResponse* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace zera_api

