#pragma once
// All databases that form one recoverable blockchain snapshot.
// Keep the inventory centralized for offline validation and startup opening.
#define ZERA_DATABASES(X) \
    X(db_headers) \
    X(db_blocks) \
    X(db_contract_supply) \
    X(db_contracts) \
    X(db_hash_index) \
    X(db_transactions) \
    X(db_validators) \
    X(db_wallets) \
    X(db_wallets_temp) \
    X(db_smart_contracts) \
    X(db_restricted_wallets) \
    X(db_block_txns) \
    X(db_contract_items) \
    X(db_validator_lookup) \
    X(db_validator_unbond) \
    X(db_proposal_ledger) \
    X(db_proposals) \
    X(db_status_fee) \
    X(db_process_ledger) \
    X(db_process_adaptive_ledger) \
    X(db_expense_ratio) \
    X(db_proposal_wallets) \
    X(db_proposals_temp) \
    X(db_delegate_vote) \
    X(db_delegate_recipient) \
    X(db_timed_txns) \
    X(db_quash_lookup) \
    X(db_quash_ledger) \
    X(db_wallet_lookup) \
    X(db_delegate_wallets) \
    X(db_fast_quorum) \
    X(db_duplicate_txn) \
    X(db_delegatees) \
    X(db_voted_proposals) \
    X(db_wallet_nonce) \
    X(db_processed_txns) \
    X(db_processed_wallets) \
    X(db_preprocessed_nonce) \
    X(db_validate_txns) \
    X(db_sc_transactions) \
    X(db_gov_txn) \
    X(db_contract_price) \
    X(db_attestation) \
    X(db_confirmed_blocks) \
    X(db_attestation_ledger) \
    X(db_validator_archive) \
    X(db_quash_ledger_lookup) \
    X(db_system) \
    X(db_gossip) \
    X(db_sc_temp) \
    X(db_allowance) \
    X(db_sc_subscriber) \
    X(db_event_management) \
    X(db_fee_tokens) \
    X(db_fee_tokens_temp) \
    X(db_staked_coins_voted) \
    X(db_staked_coins_voted_temp) \
    X(db_smart_contract_states)
